// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: structs.proto

#ifndef PROTOBUF_structs_2eproto__INCLUDED
#define PROTOBUF_structs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace structDefinitions {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_structs_2eproto();
void protobuf_AssignDesc_structs_2eproto();
void protobuf_ShutdownFile_structs_2eproto();

class Block;
class DataPackage;
class Edge;
class Header;
class MessageInfo;
class Point3D;
class Properties;
class TriangleFace;
class Vertex;

enum MessageInfo_Type {
  MessageInfo_Type_DATA = 1,
  MessageInfo_Type_RENDER = 2,
  MessageInfo_Type_BREAKPOINT = 3,
  MessageInfo_Type_ACCEPTED = 4,
  MessageInfo_Type_REJECTED = 5,
  MessageInfo_Type_ACK = 6,
  MessageInfo_Type_CLEAN = 7,
  MessageInfo_Type_HARD_RESET = 8,
  MessageInfo_Type_NO_RESET = 9
};
bool MessageInfo_Type_IsValid(int value);
const MessageInfo_Type MessageInfo_Type_Type_MIN = MessageInfo_Type_DATA;
const MessageInfo_Type MessageInfo_Type_Type_MAX = MessageInfo_Type_NO_RESET;
const int MessageInfo_Type_Type_ARRAYSIZE = MessageInfo_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageInfo_Type_descriptor();
inline const ::std::string& MessageInfo_Type_Name(MessageInfo_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageInfo_Type_descriptor(), value);
}
inline bool MessageInfo_Type_Parse(
    const ::std::string& name, MessageInfo_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageInfo_Type>(
    MessageInfo_Type_descriptor(), name, value);
}
// ===================================================================

class Properties : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.Properties) */ {
 public:
  Properties();
  virtual ~Properties();

  Properties(const Properties& from);

  inline Properties& operator=(const Properties& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Properties& default_instance();

  void Swap(Properties* other);

  // implements Message ----------------------------------------------

  inline Properties* New() const { return New(NULL); }

  Properties* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Properties& from);
  void MergeFrom(const Properties& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Properties* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double quality = 1;
  bool has_quality() const;
  void clear_quality();
  static const int kQualityFieldNumber = 1;
  double quality() const;
  void set_quality(double value);

  // optional string label = 2;
  bool has_label() const;
  void clear_label();
  static const int kLabelFieldNumber = 2;
  const ::std::string& label() const;
  void set_label(const ::std::string& value);
  void set_label(const char* value);
  void set_label(const char* value, size_t size);
  ::std::string* mutable_label();
  ::std::string* release_label();
  void set_allocated_label(::std::string* label);

  // optional int32 groupId = 3;
  bool has_groupid() const;
  void clear_groupid();
  static const int kGroupIdFieldNumber = 3;
  ::google::protobuf::int32 groupid() const;
  void set_groupid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:structDefinitions.Properties)
 private:
  inline void set_has_quality();
  inline void clear_has_quality();
  inline void set_has_label();
  inline void clear_has_label();
  inline void set_has_groupid();
  inline void clear_has_groupid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double quality_;
  ::google::protobuf::internal::ArenaStringPtr label_;
  ::google::protobuf::int32 groupid_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static Properties* default_instance_;
};
// -------------------------------------------------------------------

class Point3D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.Point3D) */ {
 public:
  Point3D();
  virtual ~Point3D();

  Point3D(const Point3D& from);

  inline Point3D& operator=(const Point3D& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point3D& default_instance();

  void Swap(Point3D* other);

  // implements Message ----------------------------------------------

  inline Point3D* New() const { return New(NULL); }

  Point3D* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Point3D& from);
  void MergeFrom(const Point3D& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Point3D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // required double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // required double z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // @@protoc_insertion_point(class_scope:structDefinitions.Point3D)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static Point3D* default_instance_;
};
// -------------------------------------------------------------------

class Vertex : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.Vertex) */ {
 public:
  Vertex();
  virtual ~Vertex();

  Vertex(const Vertex& from);

  inline Vertex& operator=(const Vertex& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vertex& default_instance();

  void Swap(Vertex* other);

  // implements Message ----------------------------------------------

  inline Vertex* New() const { return New(NULL); }

  Vertex* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Vertex& from);
  void MergeFrom(const Vertex& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Vertex* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .structDefinitions.Point3D point = 1;
  bool has_point() const;
  void clear_point();
  static const int kPointFieldNumber = 1;
  const ::structDefinitions::Point3D& point() const;
  ::structDefinitions::Point3D* mutable_point();
  ::structDefinitions::Point3D* release_point();
  void set_allocated_point(::structDefinitions::Point3D* point);

  // optional .structDefinitions.Properties prop = 2;
  bool has_prop() const;
  void clear_prop();
  static const int kPropFieldNumber = 2;
  const ::structDefinitions::Properties& prop() const;
  ::structDefinitions::Properties* mutable_prop();
  ::structDefinitions::Properties* release_prop();
  void set_allocated_prop(::structDefinitions::Properties* prop);

  // @@protoc_insertion_point(class_scope:structDefinitions.Vertex)
 private:
  inline void set_has_point();
  inline void clear_has_point();
  inline void set_has_prop();
  inline void clear_has_prop();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::structDefinitions::Point3D* point_;
  ::structDefinitions::Properties* prop_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static Vertex* default_instance_;
};
// -------------------------------------------------------------------

class Edge : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.Edge) */ {
 public:
  Edge();
  virtual ~Edge();

  Edge(const Edge& from);

  inline Edge& operator=(const Edge& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Edge& default_instance();

  void Swap(Edge* other);

  // implements Message ----------------------------------------------

  inline Edge* New() const { return New(NULL); }

  Edge* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Edge& from);
  void MergeFrom(const Edge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Edge* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .structDefinitions.Point3D v1 = 1;
  bool has_v1() const;
  void clear_v1();
  static const int kV1FieldNumber = 1;
  const ::structDefinitions::Point3D& v1() const;
  ::structDefinitions::Point3D* mutable_v1();
  ::structDefinitions::Point3D* release_v1();
  void set_allocated_v1(::structDefinitions::Point3D* v1);

  // required .structDefinitions.Point3D v2 = 2;
  bool has_v2() const;
  void clear_v2();
  static const int kV2FieldNumber = 2;
  const ::structDefinitions::Point3D& v2() const;
  ::structDefinitions::Point3D* mutable_v2();
  ::structDefinitions::Point3D* release_v2();
  void set_allocated_v2(::structDefinitions::Point3D* v2);

  // optional .structDefinitions.Properties prop = 3;
  bool has_prop() const;
  void clear_prop();
  static const int kPropFieldNumber = 3;
  const ::structDefinitions::Properties& prop() const;
  ::structDefinitions::Properties* mutable_prop();
  ::structDefinitions::Properties* release_prop();
  void set_allocated_prop(::structDefinitions::Properties* prop);

  // @@protoc_insertion_point(class_scope:structDefinitions.Edge)
 private:
  inline void set_has_v1();
  inline void clear_has_v1();
  inline void set_has_v2();
  inline void clear_has_v2();
  inline void set_has_prop();
  inline void clear_has_prop();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::structDefinitions::Point3D* v1_;
  ::structDefinitions::Point3D* v2_;
  ::structDefinitions::Properties* prop_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static Edge* default_instance_;
};
// -------------------------------------------------------------------

class TriangleFace : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.TriangleFace) */ {
 public:
  TriangleFace();
  virtual ~TriangleFace();

  TriangleFace(const TriangleFace& from);

  inline TriangleFace& operator=(const TriangleFace& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TriangleFace& default_instance();

  void Swap(TriangleFace* other);

  // implements Message ----------------------------------------------

  inline TriangleFace* New() const { return New(NULL); }

  TriangleFace* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TriangleFace& from);
  void MergeFrom(const TriangleFace& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TriangleFace* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .structDefinitions.Point3D v1 = 1;
  bool has_v1() const;
  void clear_v1();
  static const int kV1FieldNumber = 1;
  const ::structDefinitions::Point3D& v1() const;
  ::structDefinitions::Point3D* mutable_v1();
  ::structDefinitions::Point3D* release_v1();
  void set_allocated_v1(::structDefinitions::Point3D* v1);

  // required .structDefinitions.Point3D v2 = 2;
  bool has_v2() const;
  void clear_v2();
  static const int kV2FieldNumber = 2;
  const ::structDefinitions::Point3D& v2() const;
  ::structDefinitions::Point3D* mutable_v2();
  ::structDefinitions::Point3D* release_v2();
  void set_allocated_v2(::structDefinitions::Point3D* v2);

  // required .structDefinitions.Point3D v3 = 3;
  bool has_v3() const;
  void clear_v3();
  static const int kV3FieldNumber = 3;
  const ::structDefinitions::Point3D& v3() const;
  ::structDefinitions::Point3D* mutable_v3();
  ::structDefinitions::Point3D* release_v3();
  void set_allocated_v3(::structDefinitions::Point3D* v3);

  // optional .structDefinitions.Properties prop = 4;
  bool has_prop() const;
  void clear_prop();
  static const int kPropFieldNumber = 4;
  const ::structDefinitions::Properties& prop() const;
  ::structDefinitions::Properties* mutable_prop();
  ::structDefinitions::Properties* release_prop();
  void set_allocated_prop(::structDefinitions::Properties* prop);

  // @@protoc_insertion_point(class_scope:structDefinitions.TriangleFace)
 private:
  inline void set_has_v1();
  inline void clear_has_v1();
  inline void set_has_v2();
  inline void clear_has_v2();
  inline void set_has_v3();
  inline void clear_has_v3();
  inline void set_has_prop();
  inline void clear_has_prop();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::structDefinitions::Point3D* v1_;
  ::structDefinitions::Point3D* v2_;
  ::structDefinitions::Point3D* v3_;
  ::structDefinitions::Properties* prop_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static TriangleFace* default_instance_;
};
// -------------------------------------------------------------------

class Block : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.Block) */ {
 public:
  Block();
  virtual ~Block();

  Block(const Block& from);

  inline Block& operator=(const Block& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Block& default_instance();

  void Swap(Block* other);

  // implements Message ----------------------------------------------

  inline Block* New() const { return New(NULL); }

  Block* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Block& from);
  void MergeFrom(const Block& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Block* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .structDefinitions.Point3D v1 = 1;
  bool has_v1() const;
  void clear_v1();
  static const int kV1FieldNumber = 1;
  const ::structDefinitions::Point3D& v1() const;
  ::structDefinitions::Point3D* mutable_v1();
  ::structDefinitions::Point3D* release_v1();
  void set_allocated_v1(::structDefinitions::Point3D* v1);

  // required .structDefinitions.Point3D v2 = 2;
  bool has_v2() const;
  void clear_v2();
  static const int kV2FieldNumber = 2;
  const ::structDefinitions::Point3D& v2() const;
  ::structDefinitions::Point3D* mutable_v2();
  ::structDefinitions::Point3D* release_v2();
  void set_allocated_v2(::structDefinitions::Point3D* v2);

  // required .structDefinitions.Point3D v3 = 3;
  bool has_v3() const;
  void clear_v3();
  static const int kV3FieldNumber = 3;
  const ::structDefinitions::Point3D& v3() const;
  ::structDefinitions::Point3D* mutable_v3();
  ::structDefinitions::Point3D* release_v3();
  void set_allocated_v3(::structDefinitions::Point3D* v3);

  // required .structDefinitions.Point3D v4 = 4;
  bool has_v4() const;
  void clear_v4();
  static const int kV4FieldNumber = 4;
  const ::structDefinitions::Point3D& v4() const;
  ::structDefinitions::Point3D* mutable_v4();
  ::structDefinitions::Point3D* release_v4();
  void set_allocated_v4(::structDefinitions::Point3D* v4);

  // optional .structDefinitions.Properties prop = 5;
  bool has_prop() const;
  void clear_prop();
  static const int kPropFieldNumber = 5;
  const ::structDefinitions::Properties& prop() const;
  ::structDefinitions::Properties* mutable_prop();
  ::structDefinitions::Properties* release_prop();
  void set_allocated_prop(::structDefinitions::Properties* prop);

  // @@protoc_insertion_point(class_scope:structDefinitions.Block)
 private:
  inline void set_has_v1();
  inline void clear_has_v1();
  inline void set_has_v2();
  inline void clear_has_v2();
  inline void set_has_v3();
  inline void clear_has_v3();
  inline void set_has_v4();
  inline void clear_has_v4();
  inline void set_has_prop();
  inline void clear_has_prop();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::structDefinitions::Point3D* v1_;
  ::structDefinitions::Point3D* v2_;
  ::structDefinitions::Point3D* v3_;
  ::structDefinitions::Point3D* v4_;
  ::structDefinitions::Properties* prop_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static Block* default_instance_;
};
// -------------------------------------------------------------------

class MessageInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.MessageInfo) */ {
 public:
  MessageInfo();
  virtual ~MessageInfo();

  MessageInfo(const MessageInfo& from);

  inline MessageInfo& operator=(const MessageInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageInfo& default_instance();

  void Swap(MessageInfo* other);

  // implements Message ----------------------------------------------

  inline MessageInfo* New() const { return New(NULL); }

  MessageInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageInfo& from);
  void MergeFrom(const MessageInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MessageInfo_Type Type;
  static const Type DATA =
    MessageInfo_Type_DATA;
  static const Type RENDER =
    MessageInfo_Type_RENDER;
  static const Type BREAKPOINT =
    MessageInfo_Type_BREAKPOINT;
  static const Type ACCEPTED =
    MessageInfo_Type_ACCEPTED;
  static const Type REJECTED =
    MessageInfo_Type_REJECTED;
  static const Type ACK =
    MessageInfo_Type_ACK;
  static const Type CLEAN =
    MessageInfo_Type_CLEAN;
  static const Type HARD_RESET =
    MessageInfo_Type_HARD_RESET;
  static const Type NO_RESET =
    MessageInfo_Type_NO_RESET;
  static inline bool Type_IsValid(int value) {
    return MessageInfo_Type_IsValid(value);
  }
  static const Type Type_MIN =
    MessageInfo_Type_Type_MIN;
  static const Type Type_MAX =
    MessageInfo_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    MessageInfo_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return MessageInfo_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return MessageInfo_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return MessageInfo_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .structDefinitions.MessageInfo.Type type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::structDefinitions::MessageInfo_Type type() const;
  void set_type(::structDefinitions::MessageInfo_Type value);

  // @@protoc_insertion_point(class_scope:structDefinitions.MessageInfo)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static MessageInfo* default_instance_;
};
// -------------------------------------------------------------------

class Header : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  void Swap(Header* other);

  // implements Message ----------------------------------------------

  inline Header* New() const { return New(NULL); }

  Header* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 sizeOfData = 1;
  bool has_sizeofdata() const;
  void clear_sizeofdata();
  static const int kSizeOfDataFieldNumber = 1;
  ::google::protobuf::int32 sizeofdata() const;
  void set_sizeofdata(::google::protobuf::int32 value);

  // required bool endOfData = 7;
  bool has_endofdata() const;
  void clear_endofdata();
  static const int kEndOfDataFieldNumber = 7;
  bool endofdata() const;
  void set_endofdata(bool value);

  // @@protoc_insertion_point(class_scope:structDefinitions.Header)
 private:
  inline void set_has_sizeofdata();
  inline void clear_has_sizeofdata();
  inline void set_has_endofdata();
  inline void clear_has_endofdata();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 sizeofdata_;
  bool endofdata_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static Header* default_instance_;
};
// -------------------------------------------------------------------

class DataPackage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:structDefinitions.DataPackage) */ {
 public:
  DataPackage();
  virtual ~DataPackage();

  DataPackage(const DataPackage& from);

  inline DataPackage& operator=(const DataPackage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DataPackage& default_instance();

  void Swap(DataPackage* other);

  // implements Message ----------------------------------------------

  inline DataPackage* New() const { return New(NULL); }

  DataPackage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataPackage& from);
  void MergeFrom(const DataPackage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DataPackage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .structDefinitions.Vertex vertexes = 2;
  int vertexes_size() const;
  void clear_vertexes();
  static const int kVertexesFieldNumber = 2;
  const ::structDefinitions::Vertex& vertexes(int index) const;
  ::structDefinitions::Vertex* mutable_vertexes(int index);
  ::structDefinitions::Vertex* add_vertexes();
  ::google::protobuf::RepeatedPtrField< ::structDefinitions::Vertex >*
      mutable_vertexes();
  const ::google::protobuf::RepeatedPtrField< ::structDefinitions::Vertex >&
      vertexes() const;

  // repeated .structDefinitions.Edge edges = 3;
  int edges_size() const;
  void clear_edges();
  static const int kEdgesFieldNumber = 3;
  const ::structDefinitions::Edge& edges(int index) const;
  ::structDefinitions::Edge* mutable_edges(int index);
  ::structDefinitions::Edge* add_edges();
  ::google::protobuf::RepeatedPtrField< ::structDefinitions::Edge >*
      mutable_edges();
  const ::google::protobuf::RepeatedPtrField< ::structDefinitions::Edge >&
      edges() const;

  // repeated .structDefinitions.TriangleFace faces = 4;
  int faces_size() const;
  void clear_faces();
  static const int kFacesFieldNumber = 4;
  const ::structDefinitions::TriangleFace& faces(int index) const;
  ::structDefinitions::TriangleFace* mutable_faces(int index);
  ::structDefinitions::TriangleFace* add_faces();
  ::google::protobuf::RepeatedPtrField< ::structDefinitions::TriangleFace >*
      mutable_faces();
  const ::google::protobuf::RepeatedPtrField< ::structDefinitions::TriangleFace >&
      faces() const;

  // repeated .structDefinitions.Block blocks = 5;
  int blocks_size() const;
  void clear_blocks();
  static const int kBlocksFieldNumber = 5;
  const ::structDefinitions::Block& blocks(int index) const;
  ::structDefinitions::Block* mutable_blocks(int index);
  ::structDefinitions::Block* add_blocks();
  ::google::protobuf::RepeatedPtrField< ::structDefinitions::Block >*
      mutable_blocks();
  const ::google::protobuf::RepeatedPtrField< ::structDefinitions::Block >&
      blocks() const;

  // @@protoc_insertion_point(class_scope:structDefinitions.DataPackage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::structDefinitions::Vertex > vertexes_;
  ::google::protobuf::RepeatedPtrField< ::structDefinitions::Edge > edges_;
  ::google::protobuf::RepeatedPtrField< ::structDefinitions::TriangleFace > faces_;
  ::google::protobuf::RepeatedPtrField< ::structDefinitions::Block > blocks_;
  friend void  protobuf_AddDesc_structs_2eproto();
  friend void protobuf_AssignDesc_structs_2eproto();
  friend void protobuf_ShutdownFile_structs_2eproto();

  void InitAsDefaultInstance();
  static DataPackage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Properties

// optional double quality = 1;
inline bool Properties::has_quality() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Properties::set_has_quality() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Properties::clear_has_quality() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Properties::clear_quality() {
  quality_ = 0;
  clear_has_quality();
}
inline double Properties::quality() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Properties.quality)
  return quality_;
}
inline void Properties::set_quality(double value) {
  set_has_quality();
  quality_ = value;
  // @@protoc_insertion_point(field_set:structDefinitions.Properties.quality)
}

// optional string label = 2;
inline bool Properties::has_label() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Properties::set_has_label() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Properties::clear_has_label() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Properties::clear_label() {
  label_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_label();
}
inline const ::std::string& Properties::label() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Properties.label)
  return label_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Properties::set_label(const ::std::string& value) {
  set_has_label();
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:structDefinitions.Properties.label)
}
inline void Properties::set_label(const char* value) {
  set_has_label();
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structDefinitions.Properties.label)
}
inline void Properties::set_label(const char* value, size_t size) {
  set_has_label();
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structDefinitions.Properties.label)
}
inline ::std::string* Properties::mutable_label() {
  set_has_label();
  // @@protoc_insertion_point(field_mutable:structDefinitions.Properties.label)
  return label_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Properties::release_label() {
  // @@protoc_insertion_point(field_release:structDefinitions.Properties.label)
  clear_has_label();
  return label_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Properties::set_allocated_label(::std::string* label) {
  if (label != NULL) {
    set_has_label();
  } else {
    clear_has_label();
  }
  label_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), label);
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Properties.label)
}

// optional int32 groupId = 3;
inline bool Properties::has_groupid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Properties::set_has_groupid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Properties::clear_has_groupid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Properties::clear_groupid() {
  groupid_ = 0;
  clear_has_groupid();
}
inline ::google::protobuf::int32 Properties::groupid() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Properties.groupId)
  return groupid_;
}
inline void Properties::set_groupid(::google::protobuf::int32 value) {
  set_has_groupid();
  groupid_ = value;
  // @@protoc_insertion_point(field_set:structDefinitions.Properties.groupId)
}

// -------------------------------------------------------------------

// Point3D

// required double x = 1;
inline bool Point3D::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Point3D::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Point3D::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Point3D::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Point3D::x() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Point3D.x)
  return x_;
}
inline void Point3D::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:structDefinitions.Point3D.x)
}

// required double y = 2;
inline bool Point3D::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Point3D::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Point3D::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Point3D::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Point3D::y() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Point3D.y)
  return y_;
}
inline void Point3D::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:structDefinitions.Point3D.y)
}

// required double z = 3;
inline bool Point3D::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Point3D::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Point3D::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Point3D::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Point3D::z() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Point3D.z)
  return z_;
}
inline void Point3D::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:structDefinitions.Point3D.z)
}

// -------------------------------------------------------------------

// Vertex

// required .structDefinitions.Point3D point = 1;
inline bool Vertex::has_point() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vertex::set_has_point() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vertex::clear_has_point() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vertex::clear_point() {
  if (point_ != NULL) point_->::structDefinitions::Point3D::Clear();
  clear_has_point();
}
inline const ::structDefinitions::Point3D& Vertex::point() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Vertex.point)
  return point_ != NULL ? *point_ : *default_instance_->point_;
}
inline ::structDefinitions::Point3D* Vertex::mutable_point() {
  set_has_point();
  if (point_ == NULL) {
    point_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Vertex.point)
  return point_;
}
inline ::structDefinitions::Point3D* Vertex::release_point() {
  // @@protoc_insertion_point(field_release:structDefinitions.Vertex.point)
  clear_has_point();
  ::structDefinitions::Point3D* temp = point_;
  point_ = NULL;
  return temp;
}
inline void Vertex::set_allocated_point(::structDefinitions::Point3D* point) {
  delete point_;
  point_ = point;
  if (point) {
    set_has_point();
  } else {
    clear_has_point();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Vertex.point)
}

// optional .structDefinitions.Properties prop = 2;
inline bool Vertex::has_prop() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vertex::set_has_prop() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vertex::clear_has_prop() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vertex::clear_prop() {
  if (prop_ != NULL) prop_->::structDefinitions::Properties::Clear();
  clear_has_prop();
}
inline const ::structDefinitions::Properties& Vertex::prop() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Vertex.prop)
  return prop_ != NULL ? *prop_ : *default_instance_->prop_;
}
inline ::structDefinitions::Properties* Vertex::mutable_prop() {
  set_has_prop();
  if (prop_ == NULL) {
    prop_ = new ::structDefinitions::Properties;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Vertex.prop)
  return prop_;
}
inline ::structDefinitions::Properties* Vertex::release_prop() {
  // @@protoc_insertion_point(field_release:structDefinitions.Vertex.prop)
  clear_has_prop();
  ::structDefinitions::Properties* temp = prop_;
  prop_ = NULL;
  return temp;
}
inline void Vertex::set_allocated_prop(::structDefinitions::Properties* prop) {
  delete prop_;
  prop_ = prop;
  if (prop) {
    set_has_prop();
  } else {
    clear_has_prop();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Vertex.prop)
}

// -------------------------------------------------------------------

// Edge

// required .structDefinitions.Point3D v1 = 1;
inline bool Edge::has_v1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Edge::set_has_v1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Edge::clear_has_v1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Edge::clear_v1() {
  if (v1_ != NULL) v1_->::structDefinitions::Point3D::Clear();
  clear_has_v1();
}
inline const ::structDefinitions::Point3D& Edge::v1() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Edge.v1)
  return v1_ != NULL ? *v1_ : *default_instance_->v1_;
}
inline ::structDefinitions::Point3D* Edge::mutable_v1() {
  set_has_v1();
  if (v1_ == NULL) {
    v1_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Edge.v1)
  return v1_;
}
inline ::structDefinitions::Point3D* Edge::release_v1() {
  // @@protoc_insertion_point(field_release:structDefinitions.Edge.v1)
  clear_has_v1();
  ::structDefinitions::Point3D* temp = v1_;
  v1_ = NULL;
  return temp;
}
inline void Edge::set_allocated_v1(::structDefinitions::Point3D* v1) {
  delete v1_;
  v1_ = v1;
  if (v1) {
    set_has_v1();
  } else {
    clear_has_v1();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Edge.v1)
}

// required .structDefinitions.Point3D v2 = 2;
inline bool Edge::has_v2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Edge::set_has_v2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Edge::clear_has_v2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Edge::clear_v2() {
  if (v2_ != NULL) v2_->::structDefinitions::Point3D::Clear();
  clear_has_v2();
}
inline const ::structDefinitions::Point3D& Edge::v2() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Edge.v2)
  return v2_ != NULL ? *v2_ : *default_instance_->v2_;
}
inline ::structDefinitions::Point3D* Edge::mutable_v2() {
  set_has_v2();
  if (v2_ == NULL) {
    v2_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Edge.v2)
  return v2_;
}
inline ::structDefinitions::Point3D* Edge::release_v2() {
  // @@protoc_insertion_point(field_release:structDefinitions.Edge.v2)
  clear_has_v2();
  ::structDefinitions::Point3D* temp = v2_;
  v2_ = NULL;
  return temp;
}
inline void Edge::set_allocated_v2(::structDefinitions::Point3D* v2) {
  delete v2_;
  v2_ = v2;
  if (v2) {
    set_has_v2();
  } else {
    clear_has_v2();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Edge.v2)
}

// optional .structDefinitions.Properties prop = 3;
inline bool Edge::has_prop() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Edge::set_has_prop() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Edge::clear_has_prop() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Edge::clear_prop() {
  if (prop_ != NULL) prop_->::structDefinitions::Properties::Clear();
  clear_has_prop();
}
inline const ::structDefinitions::Properties& Edge::prop() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Edge.prop)
  return prop_ != NULL ? *prop_ : *default_instance_->prop_;
}
inline ::structDefinitions::Properties* Edge::mutable_prop() {
  set_has_prop();
  if (prop_ == NULL) {
    prop_ = new ::structDefinitions::Properties;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Edge.prop)
  return prop_;
}
inline ::structDefinitions::Properties* Edge::release_prop() {
  // @@protoc_insertion_point(field_release:structDefinitions.Edge.prop)
  clear_has_prop();
  ::structDefinitions::Properties* temp = prop_;
  prop_ = NULL;
  return temp;
}
inline void Edge::set_allocated_prop(::structDefinitions::Properties* prop) {
  delete prop_;
  prop_ = prop;
  if (prop) {
    set_has_prop();
  } else {
    clear_has_prop();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Edge.prop)
}

// -------------------------------------------------------------------

// TriangleFace

// required .structDefinitions.Point3D v1 = 1;
inline bool TriangleFace::has_v1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TriangleFace::set_has_v1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TriangleFace::clear_has_v1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TriangleFace::clear_v1() {
  if (v1_ != NULL) v1_->::structDefinitions::Point3D::Clear();
  clear_has_v1();
}
inline const ::structDefinitions::Point3D& TriangleFace::v1() const {
  // @@protoc_insertion_point(field_get:structDefinitions.TriangleFace.v1)
  return v1_ != NULL ? *v1_ : *default_instance_->v1_;
}
inline ::structDefinitions::Point3D* TriangleFace::mutable_v1() {
  set_has_v1();
  if (v1_ == NULL) {
    v1_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.TriangleFace.v1)
  return v1_;
}
inline ::structDefinitions::Point3D* TriangleFace::release_v1() {
  // @@protoc_insertion_point(field_release:structDefinitions.TriangleFace.v1)
  clear_has_v1();
  ::structDefinitions::Point3D* temp = v1_;
  v1_ = NULL;
  return temp;
}
inline void TriangleFace::set_allocated_v1(::structDefinitions::Point3D* v1) {
  delete v1_;
  v1_ = v1;
  if (v1) {
    set_has_v1();
  } else {
    clear_has_v1();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.TriangleFace.v1)
}

// required .structDefinitions.Point3D v2 = 2;
inline bool TriangleFace::has_v2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TriangleFace::set_has_v2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TriangleFace::clear_has_v2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TriangleFace::clear_v2() {
  if (v2_ != NULL) v2_->::structDefinitions::Point3D::Clear();
  clear_has_v2();
}
inline const ::structDefinitions::Point3D& TriangleFace::v2() const {
  // @@protoc_insertion_point(field_get:structDefinitions.TriangleFace.v2)
  return v2_ != NULL ? *v2_ : *default_instance_->v2_;
}
inline ::structDefinitions::Point3D* TriangleFace::mutable_v2() {
  set_has_v2();
  if (v2_ == NULL) {
    v2_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.TriangleFace.v2)
  return v2_;
}
inline ::structDefinitions::Point3D* TriangleFace::release_v2() {
  // @@protoc_insertion_point(field_release:structDefinitions.TriangleFace.v2)
  clear_has_v2();
  ::structDefinitions::Point3D* temp = v2_;
  v2_ = NULL;
  return temp;
}
inline void TriangleFace::set_allocated_v2(::structDefinitions::Point3D* v2) {
  delete v2_;
  v2_ = v2;
  if (v2) {
    set_has_v2();
  } else {
    clear_has_v2();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.TriangleFace.v2)
}

// required .structDefinitions.Point3D v3 = 3;
inline bool TriangleFace::has_v3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TriangleFace::set_has_v3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TriangleFace::clear_has_v3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TriangleFace::clear_v3() {
  if (v3_ != NULL) v3_->::structDefinitions::Point3D::Clear();
  clear_has_v3();
}
inline const ::structDefinitions::Point3D& TriangleFace::v3() const {
  // @@protoc_insertion_point(field_get:structDefinitions.TriangleFace.v3)
  return v3_ != NULL ? *v3_ : *default_instance_->v3_;
}
inline ::structDefinitions::Point3D* TriangleFace::mutable_v3() {
  set_has_v3();
  if (v3_ == NULL) {
    v3_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.TriangleFace.v3)
  return v3_;
}
inline ::structDefinitions::Point3D* TriangleFace::release_v3() {
  // @@protoc_insertion_point(field_release:structDefinitions.TriangleFace.v3)
  clear_has_v3();
  ::structDefinitions::Point3D* temp = v3_;
  v3_ = NULL;
  return temp;
}
inline void TriangleFace::set_allocated_v3(::structDefinitions::Point3D* v3) {
  delete v3_;
  v3_ = v3;
  if (v3) {
    set_has_v3();
  } else {
    clear_has_v3();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.TriangleFace.v3)
}

// optional .structDefinitions.Properties prop = 4;
inline bool TriangleFace::has_prop() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TriangleFace::set_has_prop() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TriangleFace::clear_has_prop() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TriangleFace::clear_prop() {
  if (prop_ != NULL) prop_->::structDefinitions::Properties::Clear();
  clear_has_prop();
}
inline const ::structDefinitions::Properties& TriangleFace::prop() const {
  // @@protoc_insertion_point(field_get:structDefinitions.TriangleFace.prop)
  return prop_ != NULL ? *prop_ : *default_instance_->prop_;
}
inline ::structDefinitions::Properties* TriangleFace::mutable_prop() {
  set_has_prop();
  if (prop_ == NULL) {
    prop_ = new ::structDefinitions::Properties;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.TriangleFace.prop)
  return prop_;
}
inline ::structDefinitions::Properties* TriangleFace::release_prop() {
  // @@protoc_insertion_point(field_release:structDefinitions.TriangleFace.prop)
  clear_has_prop();
  ::structDefinitions::Properties* temp = prop_;
  prop_ = NULL;
  return temp;
}
inline void TriangleFace::set_allocated_prop(::structDefinitions::Properties* prop) {
  delete prop_;
  prop_ = prop;
  if (prop) {
    set_has_prop();
  } else {
    clear_has_prop();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.TriangleFace.prop)
}

// -------------------------------------------------------------------

// Block

// required .structDefinitions.Point3D v1 = 1;
inline bool Block::has_v1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Block::set_has_v1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Block::clear_has_v1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Block::clear_v1() {
  if (v1_ != NULL) v1_->::structDefinitions::Point3D::Clear();
  clear_has_v1();
}
inline const ::structDefinitions::Point3D& Block::v1() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Block.v1)
  return v1_ != NULL ? *v1_ : *default_instance_->v1_;
}
inline ::structDefinitions::Point3D* Block::mutable_v1() {
  set_has_v1();
  if (v1_ == NULL) {
    v1_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Block.v1)
  return v1_;
}
inline ::structDefinitions::Point3D* Block::release_v1() {
  // @@protoc_insertion_point(field_release:structDefinitions.Block.v1)
  clear_has_v1();
  ::structDefinitions::Point3D* temp = v1_;
  v1_ = NULL;
  return temp;
}
inline void Block::set_allocated_v1(::structDefinitions::Point3D* v1) {
  delete v1_;
  v1_ = v1;
  if (v1) {
    set_has_v1();
  } else {
    clear_has_v1();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Block.v1)
}

// required .structDefinitions.Point3D v2 = 2;
inline bool Block::has_v2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Block::set_has_v2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Block::clear_has_v2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Block::clear_v2() {
  if (v2_ != NULL) v2_->::structDefinitions::Point3D::Clear();
  clear_has_v2();
}
inline const ::structDefinitions::Point3D& Block::v2() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Block.v2)
  return v2_ != NULL ? *v2_ : *default_instance_->v2_;
}
inline ::structDefinitions::Point3D* Block::mutable_v2() {
  set_has_v2();
  if (v2_ == NULL) {
    v2_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Block.v2)
  return v2_;
}
inline ::structDefinitions::Point3D* Block::release_v2() {
  // @@protoc_insertion_point(field_release:structDefinitions.Block.v2)
  clear_has_v2();
  ::structDefinitions::Point3D* temp = v2_;
  v2_ = NULL;
  return temp;
}
inline void Block::set_allocated_v2(::structDefinitions::Point3D* v2) {
  delete v2_;
  v2_ = v2;
  if (v2) {
    set_has_v2();
  } else {
    clear_has_v2();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Block.v2)
}

// required .structDefinitions.Point3D v3 = 3;
inline bool Block::has_v3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Block::set_has_v3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Block::clear_has_v3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Block::clear_v3() {
  if (v3_ != NULL) v3_->::structDefinitions::Point3D::Clear();
  clear_has_v3();
}
inline const ::structDefinitions::Point3D& Block::v3() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Block.v3)
  return v3_ != NULL ? *v3_ : *default_instance_->v3_;
}
inline ::structDefinitions::Point3D* Block::mutable_v3() {
  set_has_v3();
  if (v3_ == NULL) {
    v3_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Block.v3)
  return v3_;
}
inline ::structDefinitions::Point3D* Block::release_v3() {
  // @@protoc_insertion_point(field_release:structDefinitions.Block.v3)
  clear_has_v3();
  ::structDefinitions::Point3D* temp = v3_;
  v3_ = NULL;
  return temp;
}
inline void Block::set_allocated_v3(::structDefinitions::Point3D* v3) {
  delete v3_;
  v3_ = v3;
  if (v3) {
    set_has_v3();
  } else {
    clear_has_v3();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Block.v3)
}

// required .structDefinitions.Point3D v4 = 4;
inline bool Block::has_v4() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Block::set_has_v4() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Block::clear_has_v4() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Block::clear_v4() {
  if (v4_ != NULL) v4_->::structDefinitions::Point3D::Clear();
  clear_has_v4();
}
inline const ::structDefinitions::Point3D& Block::v4() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Block.v4)
  return v4_ != NULL ? *v4_ : *default_instance_->v4_;
}
inline ::structDefinitions::Point3D* Block::mutable_v4() {
  set_has_v4();
  if (v4_ == NULL) {
    v4_ = new ::structDefinitions::Point3D;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Block.v4)
  return v4_;
}
inline ::structDefinitions::Point3D* Block::release_v4() {
  // @@protoc_insertion_point(field_release:structDefinitions.Block.v4)
  clear_has_v4();
  ::structDefinitions::Point3D* temp = v4_;
  v4_ = NULL;
  return temp;
}
inline void Block::set_allocated_v4(::structDefinitions::Point3D* v4) {
  delete v4_;
  v4_ = v4;
  if (v4) {
    set_has_v4();
  } else {
    clear_has_v4();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Block.v4)
}

// optional .structDefinitions.Properties prop = 5;
inline bool Block::has_prop() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Block::set_has_prop() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Block::clear_has_prop() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Block::clear_prop() {
  if (prop_ != NULL) prop_->::structDefinitions::Properties::Clear();
  clear_has_prop();
}
inline const ::structDefinitions::Properties& Block::prop() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Block.prop)
  return prop_ != NULL ? *prop_ : *default_instance_->prop_;
}
inline ::structDefinitions::Properties* Block::mutable_prop() {
  set_has_prop();
  if (prop_ == NULL) {
    prop_ = new ::structDefinitions::Properties;
  }
  // @@protoc_insertion_point(field_mutable:structDefinitions.Block.prop)
  return prop_;
}
inline ::structDefinitions::Properties* Block::release_prop() {
  // @@protoc_insertion_point(field_release:structDefinitions.Block.prop)
  clear_has_prop();
  ::structDefinitions::Properties* temp = prop_;
  prop_ = NULL;
  return temp;
}
inline void Block::set_allocated_prop(::structDefinitions::Properties* prop) {
  delete prop_;
  prop_ = prop;
  if (prop) {
    set_has_prop();
  } else {
    clear_has_prop();
  }
  // @@protoc_insertion_point(field_set_allocated:structDefinitions.Block.prop)
}

// -------------------------------------------------------------------

// MessageInfo

// required .structDefinitions.MessageInfo.Type type = 1;
inline bool MessageInfo::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageInfo::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageInfo::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageInfo::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::structDefinitions::MessageInfo_Type MessageInfo::type() const {
  // @@protoc_insertion_point(field_get:structDefinitions.MessageInfo.type)
  return static_cast< ::structDefinitions::MessageInfo_Type >(type_);
}
inline void MessageInfo::set_type(::structDefinitions::MessageInfo_Type value) {
  assert(::structDefinitions::MessageInfo_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:structDefinitions.MessageInfo.type)
}

// -------------------------------------------------------------------

// Header

// required int32 sizeOfData = 1;
inline bool Header::has_sizeofdata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Header::set_has_sizeofdata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Header::clear_has_sizeofdata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Header::clear_sizeofdata() {
  sizeofdata_ = 0;
  clear_has_sizeofdata();
}
inline ::google::protobuf::int32 Header::sizeofdata() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Header.sizeOfData)
  return sizeofdata_;
}
inline void Header::set_sizeofdata(::google::protobuf::int32 value) {
  set_has_sizeofdata();
  sizeofdata_ = value;
  // @@protoc_insertion_point(field_set:structDefinitions.Header.sizeOfData)
}

// required bool endOfData = 7;
inline bool Header::has_endofdata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Header::set_has_endofdata() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Header::clear_has_endofdata() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Header::clear_endofdata() {
  endofdata_ = false;
  clear_has_endofdata();
}
inline bool Header::endofdata() const {
  // @@protoc_insertion_point(field_get:structDefinitions.Header.endOfData)
  return endofdata_;
}
inline void Header::set_endofdata(bool value) {
  set_has_endofdata();
  endofdata_ = value;
  // @@protoc_insertion_point(field_set:structDefinitions.Header.endOfData)
}

// -------------------------------------------------------------------

// DataPackage

// repeated .structDefinitions.Vertex vertexes = 2;
inline int DataPackage::vertexes_size() const {
  return vertexes_.size();
}
inline void DataPackage::clear_vertexes() {
  vertexes_.Clear();
}
inline const ::structDefinitions::Vertex& DataPackage::vertexes(int index) const {
  // @@protoc_insertion_point(field_get:structDefinitions.DataPackage.vertexes)
  return vertexes_.Get(index);
}
inline ::structDefinitions::Vertex* DataPackage::mutable_vertexes(int index) {
  // @@protoc_insertion_point(field_mutable:structDefinitions.DataPackage.vertexes)
  return vertexes_.Mutable(index);
}
inline ::structDefinitions::Vertex* DataPackage::add_vertexes() {
  // @@protoc_insertion_point(field_add:structDefinitions.DataPackage.vertexes)
  return vertexes_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::structDefinitions::Vertex >*
DataPackage::mutable_vertexes() {
  // @@protoc_insertion_point(field_mutable_list:structDefinitions.DataPackage.vertexes)
  return &vertexes_;
}
inline const ::google::protobuf::RepeatedPtrField< ::structDefinitions::Vertex >&
DataPackage::vertexes() const {
  // @@protoc_insertion_point(field_list:structDefinitions.DataPackage.vertexes)
  return vertexes_;
}

// repeated .structDefinitions.Edge edges = 3;
inline int DataPackage::edges_size() const {
  return edges_.size();
}
inline void DataPackage::clear_edges() {
  edges_.Clear();
}
inline const ::structDefinitions::Edge& DataPackage::edges(int index) const {
  // @@protoc_insertion_point(field_get:structDefinitions.DataPackage.edges)
  return edges_.Get(index);
}
inline ::structDefinitions::Edge* DataPackage::mutable_edges(int index) {
  // @@protoc_insertion_point(field_mutable:structDefinitions.DataPackage.edges)
  return edges_.Mutable(index);
}
inline ::structDefinitions::Edge* DataPackage::add_edges() {
  // @@protoc_insertion_point(field_add:structDefinitions.DataPackage.edges)
  return edges_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::structDefinitions::Edge >*
DataPackage::mutable_edges() {
  // @@protoc_insertion_point(field_mutable_list:structDefinitions.DataPackage.edges)
  return &edges_;
}
inline const ::google::protobuf::RepeatedPtrField< ::structDefinitions::Edge >&
DataPackage::edges() const {
  // @@protoc_insertion_point(field_list:structDefinitions.DataPackage.edges)
  return edges_;
}

// repeated .structDefinitions.TriangleFace faces = 4;
inline int DataPackage::faces_size() const {
  return faces_.size();
}
inline void DataPackage::clear_faces() {
  faces_.Clear();
}
inline const ::structDefinitions::TriangleFace& DataPackage::faces(int index) const {
  // @@protoc_insertion_point(field_get:structDefinitions.DataPackage.faces)
  return faces_.Get(index);
}
inline ::structDefinitions::TriangleFace* DataPackage::mutable_faces(int index) {
  // @@protoc_insertion_point(field_mutable:structDefinitions.DataPackage.faces)
  return faces_.Mutable(index);
}
inline ::structDefinitions::TriangleFace* DataPackage::add_faces() {
  // @@protoc_insertion_point(field_add:structDefinitions.DataPackage.faces)
  return faces_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::structDefinitions::TriangleFace >*
DataPackage::mutable_faces() {
  // @@protoc_insertion_point(field_mutable_list:structDefinitions.DataPackage.faces)
  return &faces_;
}
inline const ::google::protobuf::RepeatedPtrField< ::structDefinitions::TriangleFace >&
DataPackage::faces() const {
  // @@protoc_insertion_point(field_list:structDefinitions.DataPackage.faces)
  return faces_;
}

// repeated .structDefinitions.Block blocks = 5;
inline int DataPackage::blocks_size() const {
  return blocks_.size();
}
inline void DataPackage::clear_blocks() {
  blocks_.Clear();
}
inline const ::structDefinitions::Block& DataPackage::blocks(int index) const {
  // @@protoc_insertion_point(field_get:structDefinitions.DataPackage.blocks)
  return blocks_.Get(index);
}
inline ::structDefinitions::Block* DataPackage::mutable_blocks(int index) {
  // @@protoc_insertion_point(field_mutable:structDefinitions.DataPackage.blocks)
  return blocks_.Mutable(index);
}
inline ::structDefinitions::Block* DataPackage::add_blocks() {
  // @@protoc_insertion_point(field_add:structDefinitions.DataPackage.blocks)
  return blocks_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::structDefinitions::Block >*
DataPackage::mutable_blocks() {
  // @@protoc_insertion_point(field_mutable_list:structDefinitions.DataPackage.blocks)
  return &blocks_;
}
inline const ::google::protobuf::RepeatedPtrField< ::structDefinitions::Block >&
DataPackage::blocks() const {
  // @@protoc_insertion_point(field_list:structDefinitions.DataPackage.blocks)
  return blocks_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace structDefinitions

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::structDefinitions::MessageInfo_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::structDefinitions::MessageInfo_Type>() {
  return ::structDefinitions::MessageInfo_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_structs_2eproto__INCLUDED
